[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nnodely"
version = "1.0"
description = "Model-structured neural network framework for the modeling and control of physical systems"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT License", file = "LICENSE"}
authors = [
    {name = "Gastone Pietro Rosati Papini", email = "tonegas@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "matplotlib",
    "numpy",
    "onnx",
    "pandas",
    "torch",
    "reportlab"
]

[project.urls]
"Homepage" = "https://github.com/tonegas/nnodely"

[tool.setuptools]
packages = ["nnodely"]